// <auto-generated />

namespace RepositoryLayer.Interface
{
    using CommonLayer.Models;
    using RepositoryLayer.Entities;
    using System;
    using System.Collections.Generic;
    using System.Text;

    public interface IUserRL
    {
        /// <summary>
        /// Interface for User Registration
        /// </summary>
        /// <param name="userRegModel"></param>
        /// <returns></returns>
        public User Registration(UserRegModel userRegModel);

        /// <summary>
        /// Interface for UserLogin
        /// </summary>
        /// <param name="userLog"></param>
        /// <returns></returns>
        public LoginResponseModel UserLogin(UserLoginModel userLog);

        public string ForgetPassword(string email);
        public bool ResetPassword(string email, string password, string confirmPassword);
        public IEnumerable<User> GetAllUsers();
    }
}
