// <auto-generated />

namespace CommonLayer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public class CollabModel
    {
        public string CollabEmail { get; set; }

        public long NoteId { get; set; }
    }
}
