// <auto-generated />

namespace CommonLayer.Models
{
    using System;
    using System.Collections.Generic;
    using System.Text;

    public class LabelModel
    {
        public string LabelName { get; set; }
        public long NoteId { get; set; }
    }
}
