// <auto-generated />

namespace BusinessLayer.Interfaces
{
    using CommonLayer.Models;
    using RepositoryLayer.Entities;
    using System;
    using System.Collections.Generic;
    using System.Text;

    public interface IUserBL
    {
        public User Registration(UserRegModel userRegModel);
        public LoginResponseModel UserLogin(UserLoginModel userLog);

        public string ForgetPassword(string email);
        public bool ResetPassword(string email, string password, string confirmPassword);
        public IEnumerable<User> GetAllUsers();
    }
}
