// <auto-generated />

namespace BusinessLayer.Services
{
    using BusinessLayer.Interfaces;
    using CommonLayer.Models;
    using RepositoryLayer.Entities;
    using RepositoryLayer.Interface;
    using RepositoryLayer.Services;
    using System;
    using System.Collections.Generic;
    using System.Text;

    public class CollabBL : ICollabBL
    {
        private readonly ICollabRL collabRL;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="collabRL"></param>
        public CollabBL(ICollabRL collabRL)
        {
            this.collabRL = collabRL;
        }

        public bool AddCollab(CollabModel collabModel)
        {
            try
            {
                return collabRL.AddCollab(collabModel);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public IEnumerable<Collaborator> GetAllCollabs()
        {
            try
            {
                return collabRL.GetAllCollabs();
            }
            catch (Exception)
            {

                throw;
            }
        }
        public IEnumerable<Collaborator> GetCollabsByNoteId(long noteId)
        {
            try
            {
                return collabRL.GetCollabsByNoteId(noteId);
            }
            catch (Exception)
            {

                throw;
            }
        }

        public string ReomoveCollab(long collabID)
        {
            try
            {
                return collabRL.ReomoveCollab(collabID);
            }
            catch (Exception)
            {

                throw;
            }
        }
    }
}
